// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0qQmtkbZQ3f56a412tm_tuBhaFSMwDzU',
    appId: '1:34773544700:web:ae9635540923385e4cb179',
    messagingSenderId: '34773544700',
    projectId: 'raven-d8e0b',
    authDomain: 'raven-d8e0b.firebaseapp.com',
    storageBucket: 'raven-d8e0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_EsgDPPXOMUYBH_zMkDVp4M7D4RdTjU',
    appId: '1:34773544700:android:a6c6e40024b7f19b4cb179',
    messagingSenderId: '34773544700',
    projectId: 'raven-d8e0b',
    storageBucket: 'raven-d8e0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCjy-12YMP-0_K4KCloitbw57hZK3kSME',
    appId: '1:34773544700:ios:168f9ce946c86d284cb179',
    messagingSenderId: '34773544700',
    projectId: 'raven-d8e0b',
    storageBucket: 'raven-d8e0b.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCjy-12YMP-0_K4KCloitbw57hZK3kSME',
    appId: '1:34773544700:ios:168f9ce946c86d284cb179',
    messagingSenderId: '34773544700',
    projectId: 'raven-d8e0b',
    storageBucket: 'raven-d8e0b.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0qQmtkbZQ3f56a412tm_tuBhaFSMwDzU',
    appId: '1:34773544700:web:a227063a44c324c84cb179',
    messagingSenderId: '34773544700',
    projectId: 'raven-d8e0b',
    authDomain: 'raven-d8e0b.firebaseapp.com',
    storageBucket: 'raven-d8e0b.firebasestorage.app',
  );
}
